apache/pulsar-client-python

- pulsar/__init__.py
- src/authentication.cc
- tests/pulsar_test.py
https://github.com/apache/pulsar/pull/17482 supported basic authentication for Python client, but the `AuthenticationBasic` class accepts two positional arguments as the username and password. It's not good for extension. We should accept an auth param string like `AuthenticationOauth2` so that no changes are needed if the upstream C++ client's implementation changed, like
https://github.com/apache/pulsar-client-cpp/pull/37.
To be compatible with the existing API, change the first two arguments to keyword arguments. Then, add the 3rd keyword argument to represent the auth param string.
`test_basic_auth` and `test_invalid_basic_auth` are extended for this change.
> Support auth param string for Basic authentication

- README.md
- build-support/start-test-service-inside-container.sh
- tests/pulsar_test.py
When I ran `python3 ./tests/pulsar_tests.py`, I found some tests failed. However, when I went into the container that was started by `./build-support/pulsar-test-service-start.sh`, the logs are incomplete because the immediate flush is disabled by default.
Finally I found the error is caused by the relative path in tests. The certs are under `tests/test-conf` directory, but `pulsar_tests.py` uses the `test-conf/` relative path. Since `tests/run-unit-tests.sh` first goes to the `tests` directory before running the tests, CI works well. But a developer might just want to run a specific test from any possible directory, e.g.
```bash
python3 ./tests/pulsar_tests.py PulsarTest.test_tls_auth
```
Then it could fail and he cannot see complete logs.
- Modify `immediateFlush` to true
- Use absolute …
> Enhance developer experience for debugging tests and add related README

- dependencies.yaml
- pkg/mac/build-dependencies.sh
CI jobs has started failing because a new version of ZLib was released and the old one was removed. 
We need to change the URL to point to the archive so that we won't get in the same situation on next release.
> Fixed missed version of zlib

- .github/workflows/ci-build-release-wheels.yaml
- pkg/mac/build-dependencies.sh
- pkg/mac/build-mac-wheels.sh
- pkg/mac/python-3.7.patch
Fixed building Python wheels in `universal2` mode (x86_64 + arm64) for Python 3.7.
> Enable building Mac universal2 wheels for Python 3.7

- build-support/install-cpp-client.sh
- pkg/mac/build-pulsar-cpp.sh
Since it's now available, fetch the official binaries for the CPP client 3.0.0
> Fetch C++ client official release

- .github/workflows/ci-pr-validation.yaml
- .gitignore
- .gitmodules
- CMakeLists.txt
- README.md
- setup.py
- vcpkg-3.10.json
- vcpkg-3.7.json
- vcpkg-3.8.json
- vcpkg-3.9.json
- vcpkg.json
Fixes https://github.com/apache/pulsar-client-python/issues/7
The Python client cannot be built with MSVC.
CMakeLists.txt:
1. Boost.Python cannot be found on Windows. The component of Boost
cannot be `python3`. It should be a specific version like
`python310`. Therefore, find all possible components from 3.10 to 3.7
until the first component is available.
2. For MSVC, link to `pulsarWithDeps.lib` when `LINK_STATIC` is `ON` and
set the `MSVC_RUNTIME_LIBRARY` target property to `MultiThreaded`.
3. Change the suffix from `.so` to `.pyd` because Python on Windows
recognizes `*.pyd` as the dynamic library.
4. Link to Python library with MSVC, otherwise the symbos cannot be
found when linking `boost-python`.
README: tell users how to build Python client on Windows.
Add a workflow to build …
> Support building with MSVC

- README.md
- pulsar/__init__.py
- pulsar/functions/context.py
- pulsar/functions/function.py
- pulsar/functions/serde.py
Using the [numpy doc style](https://numpydoc.readthedocs.io/en/latest/format.html). This format is also compatible with `pdoc` by specifying `--docformat=numpy`.
To preview locally:
```bash
pip3 install pydoctor
pydoctor --make-html --html-viewsource-base=https://github.com/apache/pulsar-client-python/tree/main --docformat=numpy --theme=readthedocs --html-output=apidoc pulsar
cd apidoc
python3 -m http.server
```
Browse on localhost:8000.
cc @BewareMyPower @merlimat @shibd
> Improve apidoc with pydoctor tool 

- .asf.yaml
- .github/workflows/ci-pr-validation.yaml
After #28 we have an apidoc generator with raw content. Thus we'd better check the doc string syntax for every PR so that we don't introduce trivial regressions.
> [improve][ci] check python doc syntax

- build-support/copy-deps-versionfile.sh
- dependencies.yaml
- pkg/build-wheel-inside-docker.sh
- pkg/manylinux2014/Dockerfile
- pkg/manylinux_musl/Dockerfile
The current build process for Python wheels is to fetch the RPM packages of the C++ release and use the `libpulsar.so` from there. 
There are some issues due to incompatibilities between different versions of `libstdc++`, causing segmentation faults. In particular problems with callbacks and `std::function` objects compiled in different environments.
To avoid these issues, we need to compile the C++ client lib when we're building the Python wrapper.
> Fixed building of Linux wheel files

- pulsar/__init__.py
- src/config.cc
- src/consumer.cc
- tests/pulsar_test.py
apache/pulsar-client-python#39 
- Support consumer batch receive.
> [feat] Support consumer batch receive.

- pulsar/schema/schema_avro.py
This makes sure that the user get the information about avro support not being installed instead of a TypeError if the schema defitnition is not supplied
> fix: make sure that the fallback avro class has the signature as fastravro's

- .github/workflows/ci-build-release-wheels.yaml
- .github/workflows/ci-pr-validation.yaml
- build-support/copy-deps-versionfile.sh
- build-support/dep-url.sh
- build-support/install-dependencies.sh
- dependencies.yaml
- pkg/mac/build-dependencies.sh
- pkg/mac/build-pulsar-cpp.sh
- pkg/manylinux2014/Dockerfile
- pkg/manylinux_musl/Dockerfile
Currently there are many files that require the download URLs of dependencies to download them. It's hard to maintain if some download URL changed. For example, https://github.com/apache/pulsar-client-python/pull/17 updates the ZLib download URL under https://zlib.net/fossils/ for macOS build. However, the ZLib download URL for Linux is under https://github.com/madler/zlib/archive/. The same goes for the Pulsar C++ client, it's hard to test another URL because the candidates and the official releases are stored in different paths.
Add a `dep-url.sh` to provide two shell functions:
- `pulsar_cpp_base_url`: Print the base URL of the Pulsar C++ client release, there are the source code or binaries in the subpath.
- `download_dependency`: Download the source code according to the dependency …
> Simplify dependency upgrade process and upgrade Pulsar C++ client to 3.1.0

- build-support/dep-url.sh
After this PR, we can start the first Python client release.
> Upgrade Pulsar C++ client to 3.1.0

- build-support/stage-release.sh
Add a script to download and stage artifacts so that we can just use a `svn add *` command to add them to the central repo.
Take the 3.0.0-candidate-3 release as example, after configuring the `GITHUB_TOKEN` environment variable, you only need to run:
```bash
$PROJECT_DIR/build-support/stage-release.sh v3.1.0-candidate-3 3709463737
```
Then the layout of the current directory will be the same as https://dist.apache.org/repos/dist/dev/pulsar/pulsar-client-python-3.0.0-candidate-3/.
> Add a script to download and stage artifacts

- src/consumer.cc
- src/producer.cc
- tests/pulsar_test.py
Fix #84
Release the GIL while calling `producer.sendAsync()` to avoid a deadlock when PyBind is triggering the Python callback. 
* Main Thread 
1. Holds the Python GIL
2. Call `producer.send_async()`
3. Tries to acquire internal `ClientConnetion` lock
* Pulsar client internal thread
1. Holds lock on `ClientConnection`
2. Receives ack from the broker
3. Triggers callback
4. PyBind11 acquires GIL <---- Deadlock
The problem is the different behavior in PyBind from Boost::Python. 
We always need to make sure we release the GIL before making any call to C++ that potentially acquires any mutexes
> Fixed deadlock in producer.send_async

- RELEASE.md
Adopt the same versioning rule with the Node.js client, see https://github.com/apache/pulsar-client-node/pull/287.
Add an extra step to commit the version update directly before pushing the tag. For example, https://github.com/apache/pulsar-client-python/commit/fda50867a9c7bf927309527fade2f53eb3907bed
> Update the release process for versioning

- pulsar/schema/definition.py
Addresses Issue #31 - we should access a string representation of the given object rather than assuming that the object itself can be concatenated with a string.
> Issue #31 - Access name attribute of any type object

- pulsar/__init__.py
- src/message.cc
@BewareMyPower sorry this took so long, got distracted by some other things. I didn't realize this was already implemented in the C++ client .... at least if i'm not crazy :) So basically I just pulled a binding (same as the __str__ binding) for __repr__, and now the MessageId object looks like the following. Is this sufficient for purposes of this task?
> #66: Add Human-readable description of MessageId object

- pulsar/__init__.py
This does a simple check to see whether the object passed to create_reader() is a Python MessageId object - if so, it accesses the _pulsar.MessageId object that's a property before proceeding with the relevant checks and routine.
> Issue #37 : Allow passing pulsar.MessageId instance to create_reader()

- RELEASE.md
In addition, fix some wrong steps of the release process
> [docs] Describe how to install the candidate wheels

- setup.py
Fixes https://github.com/apache/pulsar-client-python/issues/67
This PR fixes the client cannot be installed with `[avro]`. Take Python 3.11 on Windows as example:
```PowerShell
D:\> py -m pip install 'pulsar_client-3.2.0a1-cp311-cp311-win_amd64.whl[avro]'
Processing d:\pulsar_client-3.2.0a1-cp311-cp311-win_amd64.whl
Requirement already satisfied: certifi in c:\users\xuyunze\appdata\local\programs\python\python311\lib\site-packages (from pulsar-client==3.2.0a1) (2022.12.7)
Collecting fastavro==1.7.3
Using cached fastavro-1.7.3-cp311-cp311-win_amd64.whl (406 kB)
pulsar-client is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.
Installing collected packages: fastavro
Successfully installed fastavro-1.7.3
[notice] A …
```
> Upgrade fastavro to 1.7.3

- setup.py
The new BK client is now working with newer version of Grpc, so we can upgrade and use Grpc >1.37 which comes with pre-packaged binaries.
> Update to bookkeeper client 4.16.1

- build-support/dep-url.sh
- dependencies.yaml
Fixes https://github.com/apache/pulsar-client-python/issues/116
https://github.com/apache/pulsar-client-cpp/pull/266 is included in the C++ client 3.2.0 so that #116 will be fixed.
> Bump the C++ client to 3.2.0

- .github/workflows/ci-pr-validation.yaml
- build-support/docker-compose-pulsar-oauth2.yml
- pulsar/__init__.py
- tests/oauth2_test.py
Add tests to verify the changes of
https://github.com/apache/pulsar-client-cpp/pull/249 work for the Python client.
Add docs to describe valid JSON fields used to create an `AuthenticationOauth2` instance.
> Add docs and tests for AuthenticationOauth2

- pulsar/__init__.py
- src/consumer.cc
- tests/pulsar_test.py
Fixes https://github.com/apache/pulsar-client-python/issues/114
Currently the `acknowledge` and `acknowledge_cumulative` methods are all asynchronous. Even if any error happened, no exception would be raised. For example, when acknowledging cumulatively on a consumer whose consumer type is Shared or KeyShared, no error happens.
- Change these methods to synchronous and raise exceptions if the acknowledgment failed.
- Add `PulsarTest.test_acknowledge_failed` to test these failed cases.
- Improve the documents to describe which exceptions could be raised in which cases.
> Make acknowledge APIs synchronous and improve the documents

- src/reader.cc
Now that the C++ client supports `reader.readNextAsync()` we can remove the hacky way in which the `reader.read_next()` wrapper was implemented.
> Use readNextAsync for reader.read_next()

- src/utils.cc
- src/utils.h
Fix #122 
When call an async method on Pulsar C++ client, we need to be releasing the GIL to avoid a deadlock between that and the producer lock.
> Release the GIL before any call to async methods

- pulsar/__init__.py
- pulsar/schema/schema.py
- pulsar/schema/schema_avro.py
- src/client.cc
- src/message.cc
- tests/schema_test.py
Fixes https://github.com/apache/pulsar-client-python/issues/108
Currently the Python client uses the reader schema, which is the schema of the consumer, to decode Avro messages. However, when the writer schema is different from the reader schema, the decode will fail.
Add `attach_client` method to `Schema` and call it when creating consumers and readers. This method stores a reference to a `_pulsar.Client` instance, which leverages the C++ APIs added in https://github.com/apache/pulsar-client-cpp/pull/257 to fetch schema info. The `AvroSchema` class fetches and caches the writer schema if it is not cached, then use both the writer schema and reader schema to decode messages.
Add `test_schema_evolve` to test consumers or readers can decode any message whose writer schema is different with …
> Fetch writer schema to decode Avro messages

- README.md
- RELEASE.md
- pulsar/__init__.py
https://github.com/apache/pulsar-client-python/issues/85#issuecomment-1531069608
Some targets in the API docs are referenced from the `_pulsar` module, while the `pydoctor` command does not generate API docs for it. It's not friendly to users, e.g. they cannot find which values could `_pulsar.ConsumerType` be.
```
pulsar/__init__.py:695: Cannot find link target for "_pulsar.ConsumerType"
```
Fix the documents to describe how to include the API docs for the `_pulsar` module when generating API docs. It also fixes some other warnings when running the `pydoctor` command.
> Include the C extension when generating API docs

- .gitignore
- pulsar/__init__.py
- src/config.cc
- src/enums.cc
- tests/pulsar_test.py
The pulsar python client lacks support for defining KeyShared behaviour like out of order message delivery and sticky-hash, auto-hash for consumers in KeyShared mode. This PR adds full support. The user can now provide a KeySharedPolicy when starting a consumer with client.subscribe() #47 
The ConsumerConfiguration::KeySharedPolicy and related setter/getter are now exposed to the Python client in this PR.
- Added pybind11 enum for KeySharedMode in src/enums.cc.
- Added pybind11 class for KeySharedPolicy in src/config.cc.
- Modified pybind11 class for ConsumerConfiguration and added function to set KeySharedPolicy and function to read KeySharedPolicy.
- Added KeySharedPolicy wrapper to pulsar/__init__.py. This wrapper handles KeySharedPolicy initialization and does some value validation.
- …
> [Enhancement/Feature Issue #47] Added support for KeySharedPolicy for the consumer when in KeyShared mode.

- RELEASE.md
https://github.com/apache/pulsar-client-python/pull/126 adds the instruction to include the `_pulsar` C module when generating the API docs. However, it does not work when the library is installed from `pip`. It only works when the wheel is installed from `dist/*.whl` that is generated by the `python3 setup.py bdist_wheel` command in the README.
The reason is the official Python wheel uses `auditwheel` to package all dynamic libraries, so the `_pulsar.so` depends on another dynamic library in the relative path. e.g.
```bash
$ ldd ~/.local/lib/python3.8/site-packages/_pulsar.cpython-38-x86_64-linux-gnu.so
libpulsar-b6dad138.so => /home/xyz/.local/lib/python3.8/site-packages/pulsar_client.libs/libpulsar-b6dad138.so (0x00007f8dc09b3000)
...
```
If we copy the …
> [docs] Fix the incorrect API docs generation steps in the release process

- CMakeLists.txt
We need to link the Python shared library on non-Windows systems as well. Otherwise, some link errors might happen.
> Fix link failure on macOS

- pulsar/__init__.py
- src/config.cc
- tests/pulsar_test.py
- tests/test-conf/standalone-ssl.conf
- tests/test-conf/standalone.conf
#76 
- Expose batch index ack option.
- Add batch index ack unit test to cover it.
(Your PR needs to update docs and you will update later)
(Please explain why)
(Your PR contains doc changes)
(Docs have been already added)
> feat: support batch index ack.

- pulsar/__init__.py
- src/config.cc
- src/enums.cc
- tests/pulsar_test.py
#74 
- Expose the producer access mode option.
- Add unit test to cover it.
(Your PR needs to update docs and you will update later)
(Please explain why)
(Your PR contains doc changes)
(Docs have been already added)
Need to add examples docs on here: https://pulsar.apache.org/docs/3.0.x/client-libraries-producers/#configure-access-mode
> feat: support producer access mode.

- pkg/mac/build-dependencies.sh
- pkg/mac/build-pulsar-cpp.sh
Recently after the runner image was upgraded, the macOS build failed with `symbol not found in flat namespace (_EVP_PKEY_get_bn_param)`.
See https://github.com/apache/pulsar-client-python/actions/runs/5805986979/job/15740588663?pr=134
There are actually two issues.
One is that when building the C++ client on macOS, `/usr/local/opt/openssl/` will be firstly searched if `OPENSSL_ROOT_DIR` is not defined.
https://github.com/apache/pulsar-client-cpp/blob/1e7d259bb94379ef6e4618fdac283912d0be6861/CMakeLists.txt#L136
It should be fixed at the C++ client side but we can also have a workaround here by defining the `OPENSSL_ROOT_DIR` variable.
The other is that when building the libcurl, the headers from `/usr/local/include/openssl/` were included, see the logs:
``` …
```
> Fix the OpenSSL 3.x symbols not found on macOS build

- dependencies.yaml
- pkg/mac/build-dependencies.sh
- pulsar/__init__.py
- src/config.cc
- tests/pulsar_test.py
Upgrade the C++ client to 3.3.0 and deprecate the `log_conf_file_path`
config due to https://github.com/apache/pulsar-client-cpp/pull/283.
There is another issue that after
https://github.com/apache/pulsar-client-cpp/pull/290, the CMakeLists.txt
from the C++ client finds the protobuf package with config mode. To fix
it, install the OpenSSL via CMake instead of the autotools.
> Upgrade the C++ client to 3.3.0 

- pulsar/__init__.py
- src/config.cc
- src/enums.cc
- tests/pulsar_test.py
Support pattern subscription non-persistent topic.
- Expose `RegexSubscriptionMode` to support pattern subscribe `all/persistent only/non-persistent-only` topic.
- Add Regex subscription unit test to cover when RegexSubscriptionMode = AllTopic case. More case cover by cpp clients.
(Your PR needs to update docs and you will update later)
- [] `doc-not-needed` 
(Please explain why)
(Your PR contains doc changes)
(Docs have been already added)
> feat: support pattern subscription non persistent topic.

- pulsar/__init__.py
- src/config.cc
- tests/pulsar_test.py
#98 Support dead letter topic.
- Add  `ConsumerDeadLetterPolicy `.
- Add dlq_policy param on the `client.subscribe` method.
- Add `test_dead_letter_policy` to cover trigger send dlq topic by `redeliver_unacknowledged_messages `, other case covered by cpp client.
(Your PR needs to update docs and you will update later)
(Please explain why)
(Your PR contains doc changes)
(Docs have been already added)
> feat: Support dead letter topic.

- pulsar/schema/definition.py
- pulsar/schema/schema.py
- tests/schema_test.py
The client is not correctly following [Avro's type promotion rules](https://avro.apache.org/docs/1.11.1/specification/#schema-resolution), leading to a potential problem with data serialization and deserialization.
The expected behavior is that the Python client should correctly follow Avro's type promotion rules and perform type conversion when necessary, ensuring compatibility. However the actual behavior is that the Python client's schema deserialization is too strict, and type promotion is not happening as expected.
- Support schema field type promotion when validating the python type
- Convert the field value to the desired compatible python type
> [feat] Support schema field type promotion

- build-support/pulsar-test-service-start.sh
- build-support/start-test-service-inside-container.sh
- tests/pulsar_test.py
Migrate the PRs from the pulsar-client-cpp repo:
- https://github.com/apache/pulsar-client-cpp/pull/297
- https://github.com/apache/pulsar-client-cpp/pull/236
- https://github.com/apache/pulsar-client-cpp/pull/340
> Improve the developer experience when running tests

- pulsar/__init__.py
This PR adds type annotations for enum parameters in various methods in the `pulsar-client-python` package. The goal of these changes is to improve the clarity and readability of the code, and to provide better hints to developers about the expected types of the parameters. 
The following methods have been modified to include type annotations for their enum parameters:
- `Client.create_producer`
- `Client.subscribe`
- `Client.create_reader`
For example, in the `Client.create_producer` method, the `compression_type` parameter was previously defined as `compression_type=CompressionType.NONE`, but now it is defined as `compression_type: CompressionType = CompressionType.NONE`.
The addition of these type annotations will make the code easier to read and understand. It will also provide better …
> Add type annotations for enum parameters in methods

- .github/workflows/ci-pr-validation.yaml
- setup.py
See https://nvd.nist.gov/vuln/detail/CVE-2023-1428
> Upgrade grpcio to 1.60.0 to fix CVE-2023-1428

- RELEASE.md
The command in the release doc is incorrect. It will lose the double quotes for the version.
> Fix incorrect command in release doc

- .github/workflows/ci-build-release-wheels.yaml
There is an error when building the wheel for python12:
```
Dockerfile:35
--------------------
33 |     ENV PYTHON_LIBRARIES   /opt/python/${PYTHON_SPEC}/lib/python${PYTHON_VERSION}
34 |     
35 | >>> RUN pip3 install pyyaml
36 |     
37 |     ADD .build/dependencies.yaml /
--------------------
```
More context: https://github.com/apache/pulsar-client-python/actions/runs/7246274042/job/19737879474#step:6:237
The python spec name is incorrect in the github release wheels workflow. These are all specs in the manylinux2014:
```
[root@82c96c919b6f /]# cd /opt/python/
[root@82c96c919b6f python]# ll
total 0
lrwxrwxrwx 1 root root 30 Dec 18 19:58 cp310-cp310 -> /opt/_internal/cpython-3.10.13
lrwxrwxrwx 1 root root 29 Dec 18 19:57 cp311-cp311 -> /opt/_internal/cpython-3.11.7
lrwxrwxrwx 1 root …
```
> Fix incorrect python spec name for release wheels workflow

- RELEASE.md
The current upgrade version command in RELEASE.md will fail the release CI:
```
ERROR: pulsar_client-"3.4.0"-cp37-*-macosx_10_15_universal2.whl is not a supported wheel on this platform.
```
https://github.com/apache/pulsar-client-python/actions/runs/7269467100/job/19807133709#step:7:196
This PR fix this issue.
> Fix incorrect version upgrade command in RELEASE.md

- src/consumer.cc
- tests/pulsar_test.py
Fixes https://github.com/apache/pulsar-client-python/issues/178
https://github.com/apache/pulsar-client-python/pull/121 introduces a regression that when `negative_acknowledge` accepts a message ID, the underlying `acknowledgeAsync` method will be called.
Fix the `Consumer_negative_acknowledge_message_id` method and add the test for negative acknowledging message IDs in `test_redelivery_count`.
> Fix negative acknowledge on a message ID does not work

- .github/workflows/ci-build-release-wheels.yaml
The windows CI title missing the python version: https://github.com/apache/pulsar-client-python/actions/runs/7320564743/job/19942264135 The Ci title points to the incorrect matrix.
This PR fixes this issue.
> Fix windows release CI doesn't show the python version

- .github/workflows/ci-build-release-wheels.yaml
- .github/workflows/ci-pr-validation.yaml
- pkg/mac/build-dependencies.sh
There are some errors blocking the CI:
https://github.com/apache/pulsar-client-python/actions/runs/7321925272/job/19942911045?pr=181
https://github.com/apache/pulsar-client-python/actions/runs/7320564743/job/19942264377
The python 3.12 has removed the setuptools for the default dependency by this PR: https://github.com/python/cpython/issues/95299
> [gh-95299](https://github.com/python/cpython/issues/95299): Do not pre-install setuptools in virtual environments created with [venv](https://docs.python.org/3/library/venv.html#module-venv). This means that distutils, setuptools, pkg_resources, and easy_install will no longer available by default; to access these run pip install setuptools in the [activated](https://docs.python.org/3/library/venv.html#venv-explanation) virtual environment. …
> Fix missing dependency of setuptools

- .github/workflows/ci-build-release-wheels.yaml
- .github/workflows/ci-pr-validation.yaml
- README.md
- RELEASE.md
- build-support/install-dependencies.sh
- pkg/mac/build-dependencies.sh
- setup.py
- tests/schema_test.py
The `avro` component cannot be installed with Python 3.12 because the depended `fastavro` dependency is 1.7.3, which is not compatible with Python 3.12. However, the newer fastavro dependencies all do not support Python 3.7, which has already reached the EOL (2023-06-27).
- Upgrade the fastavro dependency to 1.9.2
- Add the workflows to run tests for the lowest and highest supported Python versions (3.8 and 3.12).
- Fix the documents
> Fix the incompatibility with Python 3.12 and drop the support for 3.7

- pulsar/__init__.py
See https://github.com/apache/pulsar-client-python/issues/184
It should be documented that the callback should not throw any exception when passed to `send_async`.
> Document the requirement for the send_async method

- RELEASE.md
PyPI has discontinued the use of plain usernames and passwords for login. It is now necessary to generate and obtain an API token for PyPI.
The [sample PR for generating the release note](https://github.com/apache/pulsar-site/pull/343) is outdated. The pulsar-site has changed its structure. This PR uses a [new sample PR](https://github.com/apache/pulsar-site/pull/761) instead.
> Fix the release doc for PyPI login and release note sample PR

- pulsar/__init__.py
- pulsar/asyncio.py
- src/client.cc
- src/producer.cc
- tests/asyncio_test.py
- tests/run-unit-tests.sh
Master issue: https://github.com/apache/pulsar-client-python/issues/55
Introduce a `pulsar.asyncio` module that includes the asynchronous APIs to work with Python asyncio module.
Example:
```python
async def main():
client = Client('pulsar://localhost:6650')
try:
producer = await client.create_producer('topic')
msg_id = await producer.send('msg'.encode())
await producer.close()
except PulsarException as e:
error = e.error()
await client.close()
```
The creation of `Client` reuses the same keyword arguments from `pulsar.Client` but the options for creating producer and sending messages are not added yet.
> [asyncio] Support creating producer and sending messages

- pulsar/__init__.py
Fixes https://github.com/apache/pulsar-client-python/issues/194
When the Python logger is configured as the logger, during the exit process of a Python script, the default logger will be used for logging instead because the Python logger is unavailable after the interpreter is finalized. It might lead to some unexpected outputs to standard output.
> [docs] Add guide to avoid logs from the default logger

- pulsar/schema/schema_avro.py
See
https://github.com/apache/pulsar-client-python/blob/f9b2d168ae85f289d6ee043cd81791d569ba8844/pulsar/schema/schema_avro.py#L92C32-L92C69
When `self._decode_bytes(msg.data(), writer_schema)` failed, the error log is still `Failed to get schema info`, which is confusing.
Modify the error message. Even if it failed at
`self._get_writer_schema(topic, version)`, there would still be error logs from the C++ client.
> Fix incorrect logs when a message failed to be decoded with the writer schema

- pulsar/__init__.py
- src/consumer.cc
- tests/pulsar_test.py
Catch up for https://github.com/apache/pulsar-client-cpp/pull/360
> Add Consumer.consumer_name() API

- setup.py
When using the Alpine base image in Pulsar, there's a need to compile grpcio from source when 1.60.0 version is required. It's better to allow grpcio version 1.59.3 so that Alpine's py3-grpcio can be used to fulfill the requirement.
Please see https://github.com/apache/pulsar/pull/22613 for more context. 
- downgrade grpcio dependency to 1.59.3
- there's no specific minimum version constraint originating from pulsar-client-python
- grpcio is required by apache-bookkeeper-client. the dependencies are defined in https://github.com/apache/bookkeeper/blob/master/stream/clients/python/setup.py the version in this file is >= 1.8.2
- the grpcio minimum version was set to 1.60.0 in this commit: https://github.com/apache/pulsar-client-python/commit/162afd53bda321992223cb209a509ee1c46f870a . The …
> Set grpcio minimum version to 1.59.3 so that Alpine py3-grpcio can be used

- pulsar/__init__.py
- tests/pulsar_test.py
Currently the `seek` method of `Consumer` or `Reader` can only accept the `MessageId` from the `_pulsar` module, which is the underlying C extension that should not be exposed. If a `MessageId` instance from the `pulsar` module is passed as the argument, this method will fail.
> Support seek a MessageId from pulsar module

- .github/workflows/ci-build-release-wheels.yaml
- .github/workflows/ci-pr-validation.yaml
- README.md
Python 3.8 reached EOL at Oct.2024. See https://devguide.python.org/versions/
> Support Python 3.13 and drop the support for Python 3.8

- .github/workflows/ci-build-release-wheels.yaml
- pkg/mac/build-mac-wheels.sh
Currently the build workflow for macOS wheels run on macos-14 runner so that the wheel's target macOS version is 14. This is because the `-mmacosx-version-min` option is not specified when building Python from source.
You can find the following log in https://github.com/apache/pulsar-client-python/actions/runs/12878584451/job/35904753892
```
checking which MACOSX_DEPLOYMENT_TARGET to use... 14.7
```
We need to add `MACOSX_DEPLOYMENT_TARGET` as the environment variable, see https://github.com/python/cpython/blob/ec91e1c2762412f1408b0dfb5d281873b852affe/configure#L10759
Here we set it with 13 because 13 is the current minimum maintained version, see https://en.wikipedia.org/wiki/MacOS_version_history
> Set the minimum macOS version to 13

- RELEASE.md
- The latest 3.6.0 supports Python 3.9 to 3.13 now
- `twine upload` now does not accept a username. It only accepts an API token.
> Update the release process for twine upload and supported versions

- pkg/build-wheel-inside-docker.sh
- pkg/manylinux2014/pulsar-client-cpp-3.7.0.patch
Fixes https://github.com/apache/pulsar-client-python/issues/242
Fixes https://github.com/apache/pulsar-client-python/issues/243
Fixes https://github.com/apache/pulsar-client-python/issues/245
Add a patch to avoid linking to libgcc and libstdc++.
> Fix conflicts with other python libraries due to static link to libgcc and libstdc++

- pulsar/__init__.py
- src/config.cc
- tests/pulsar_test.py
With this PR, we will be able to control the printed stats.
The default interval (600 seconds) excessively prints stats when you have thousands of clients.
We have this feature on [Java client](https://stackoverflow.com/questions/75819534/how-to-disable-client-statistic-message-when-using-python-pulsar-client) and I wanted to add it for Python.
> add stats_interval_in_seconds parameter to the client configuration

- pulsar/__init__.py
- src/config.cc
- tests/pulsar_test.py
Migrate https://github.com/apache/pulsar-client-cpp/pull/12
> Add separated TLS transport configs

- pulsar/__init__.py
- tests/pulsar_test.py
Currently, `Producer.send` returns a `_pulsar.MessageId` instance, `Consumer.receive` returns a `MessageId` whose `message_id()` method returns a `_pulsar.MessageId` instance. This forces users to access the type from the C extension module (`_pulsar`).
This patch adds a `MessageId.wrap` class method to convert the type from the C extension to the type in the `pulsar` module. In addition, it exposes the comparison methods for `MessageId` and allows accepting a `MessageId` instance for `acknowledge` and `acknowledge_cumulative` methods.
> Support constructing MessageId from results of send() and receive()

- build-support/dep-url.sh
- dependencies.yaml
- pulsar/__init__.py
- pulsar/tableview.py
- src/client.cc
- src/table_view.cc
- tests/run-unit-tests.sh
- tests/table_view_test.py
Fixes #217 
Upgrade the C++ client to 3.7.1 to include this fix: https://github.com/apache/pulsar-client-cpp/pull/487
Compared to the Java `TableView` API, only a few methods are added.
`keySet()`, `values()` and `entrySet()` can be implemented by `for_each`. Take `entrySet()` for example:
```python
entries = dict()
table_view.for_each(lambda key, value: entries.__setitem__(key, value))
```
`isEmpty()` can be implemented by `__len__()` and `containsKey()` can be implemented by `get()`.
`listen()` and `refresh()` are not added because it's also missed in the C++ client.
> Support TableView

- pulsar/__init__.py
- src/message.cc
- tests/pulsar_test.py
This is a catch up for Java's `MessageId#fromByteArrayWithTopic`.
The topic name is not a part of message id's protobuf definition, while the multi-topics consumer requires a message id with topic name set. There is no way to create a message id with topic name set from the serialized bytes.
With this patch, users should serialize message id, as well as the topic name. During the deserialization, pass the topic name as the 2nd argument of `MessageId.deserialize`.
> Support deserializing a message id from bytes and topic

- setup.py
We are limiting the max protobuf version to 3.20.3, though this version is very old and now has a reported vulnerability: https://avd.aquasec.com/nvd/2025/cve-2025-4565/
> Remove version upper bound for protobuf dependency
